// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function textError(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function requireAuth(ctx) {
  return ctx.isAuthenticated() ? null : textError("Not authenticated");
}
function jsonResult(data) {
  return {
    content: [{ type: "text", text: JSON.stringify(data) }],
    structuredContent: { data }
  };
}

// src/lib/mcp/tools/get-my-profile.ts
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Get the signed-in user's Affinity profile, including bio, interests and accessibility preferences.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const { data, error } = await supabaseForUser(ctx).from("profiles").select("*").eq("id", ctx.getUserId()).maybeSingle();
    if (error) return textError(error.message);
    if (!data) return textError("No profile found for this user yet.");
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/update-my-profile.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^3.25.76";
var update_my_profile_default = defineTool2({
  name: "update_my_profile",
  title: "Update my profile",
  description: "Update fields on the signed-in user's Affinity profile. Only provided fields are changed.",
  inputSchema: {
    display_name: z.string().trim().optional().describe("Public display name."),
    bio: z.string().optional().describe("Short profile bio."),
    pronouns: z.string().optional(),
    location: z.string().optional(),
    country: z.string().optional(),
    interests: z.array(z.string()).optional().describe("List of interests."),
    accessibility_preferences: z.array(z.string()).optional().describe("Accessibility preferences."),
    communication_style: z.string().optional(),
    support_needs: z.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const updates = Object.fromEntries(Object.entries(input).filter(([, v]) => v !== void 0));
    if (Object.keys(updates).length === 0) return textError("No fields provided to update.");
    const { data, error } = await supabaseForUser(ctx).from("profiles").update(updates).eq("id", ctx.getUserId()).select().maybeSingle();
    if (error) return textError(error.message);
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/list-conversations.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_conversations_default = defineTool3({
  name: "list_conversations",
  title: "List conversations",
  description: "List the signed-in user's Affinity conversations with the other participant's public profile.",
  inputSchema: {
    limit: z2.number().int().optional().describe("Maximum conversations to return (default 20, max 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const take = Math.min(Math.max(limit ?? 20, 1), 50);
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const { data: mine, error } = await supabase.from("conversation_participants").select("conversation_id").eq("user_id", userId);
    if (error) return textError(error.message);
    const ids = (mine ?? []).map((r) => r.conversation_id).slice(0, take);
    if (ids.length === 0) return jsonResult([]);
    const { data: others } = await supabase.from("conversation_participants").select("conversation_id, user_id").in("conversation_id", ids).neq("user_id", userId);
    const otherIds = [...new Set((others ?? []).map((o) => o.user_id))];
    const { data: profiles } = await supabase.rpc("get_public_profiles", { _ids: otherIds });
    const byId = new Map((profiles ?? []).map((p) => [p.id, p]));
    return jsonResult(
      ids.map((id) => {
        const other = (others ?? []).find((o) => o.conversation_id === id);
        return {
          conversation_id: id,
          other_user_id: other?.user_id ?? null,
          other_profile: other ? byId.get(other.user_id) ?? null : null
        };
      })
    );
  }
});

// src/lib/mcp/tools/list-messages.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_messages_default = defineTool4({
  name: "list_messages",
  title: "List messages",
  description: "Read recent messages in one of the signed-in user's Affinity conversations, oldest first.",
  inputSchema: {
    conversation_id: z3.string().describe("The conversation UUID, from list_conversations."),
    limit: z3.number().int().optional().describe("Maximum messages to return (default 30, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ conversation_id, limit }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const take = Math.min(Math.max(limit ?? 30, 1), 100);
    const { data, error } = await supabaseForUser(ctx).from("messages").select("id, conversation_id, sender_id, type, content, duration, created_at").eq("conversation_id", conversation_id).order("created_at", { ascending: false }).limit(take);
    if (error) return textError(error.message);
    return jsonResult((data ?? []).reverse());
  }
});

// src/lib/mcp/tools/send-message.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z4 } from "npm:zod@^3.25.76";
var send_message_default = defineTool5({
  name: "send_message",
  title: "Send message",
  description: "Send a text message as the signed-in user in one of their Affinity conversations.",
  inputSchema: {
    conversation_id: z4.string().describe("The conversation UUID, from list_conversations."),
    content: z4.string().trim().min(1).describe("Message text to send.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ conversation_id, content }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const { data, error } = await supabaseForUser(ctx).from("messages").insert({ conversation_id, sender_id: ctx.getUserId(), content, type: "text" }).select().maybeSingle();
    if (error) return textError(error.message);
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/browse-profiles.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z5 } from "npm:zod@^3.25.76";
var browse_profiles_default = defineTool6({
  name: "browse_profiles",
  title: "Browse member profiles",
  description: "Browse public Affinity member profiles to discover potential matches. Returns only public fields.",
  inputSchema: {
    limit: z5.number().int().optional().describe("Maximum profiles to return (default 10, max 30)."),
    interest: z5.string().optional().describe("Optional interest keyword to filter on.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, interest }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const take = Math.min(Math.max(limit ?? 10, 1), 30);
    let query = supabaseForUser(ctx).from("profiles").select("id, display_name, bio, pronouns, location, country, interests, accessibility_preferences, avatar_url").neq("id", ctx.getUserId()).limit(take);
    if (interest) query = query.contains("interests", [interest]);
    const { data, error } = await query;
    if (error) return textError(error.message);
    return jsonResult(data ?? []);
  }
});

// src/lib/mcp/index.ts
var projectRef = "ptwhpulmarayfhfsgryc";
var mcp_default = defineMcp({
  name: "affinity-mcp",
  title: "Affinity",
  version: "0.1.0",
  instructions: "Tools for Affinity, an inclusive dating and community app. Use get_my_profile / update_my_profile for the signed-in member's profile, browse_profiles to discover members, and list_conversations, list_messages and send_message for chats. All tools act as the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_profile_default, update_my_profile_default, browse_profiles_default, list_conversations_default, list_messages_default, send_message_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
